version: "3"
services:
  flutter_sample:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
      args:
        WORKDIR: /home/developer/project
    volumes:
      - .:/home/developer/project
      - ${USERPROFILE-~}/.ssh:/home/developer/.ssh
    image: flutter_sample-image
    container_name: flutter_sample-container
    tty: true
    # env_file: .env # shellスクリプト内でも環境変数として使用するため
    ports:
      - "8080:8080"
