name: gh-pages

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "8"
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "2.2.1"
      - name: Install dependencies
        run: flutter pub get
        working-directory: ./flutter_tutorial
      - name: replace base path
        run: sed -i 's/<base[^>]*>//g' index.html
        working-directory: ./flutter_tutorial/web
      - name: build
        run: flutter build web
        working-directory: ./flutter_tutorial
      # - name: replace path
      #   run: sed -i 's+"/"+""+g' flutter_service_worker.js
      #   working-directory: ./flutter_tutorial/build/web
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./flutter_tutorial/build/web/
